package mybatis.dao;

import mybatis.model.CarClient;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CarClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR_CLIENT
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    int insert(CarClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR_CLIENT
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    List<CarClient> selectAll();

}