package mybatis.dao;

import mybatis.model.CarClient;
import mybatis.model.Client;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    Client selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    List<Client> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    int updateByPrimaryKey(Client record);



    List<Client> getSelectedClients(Integer carId);
}