package mybatis.dao;

import mybatis.model.Dealership;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface DealershipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALERSHIP
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALERSHIP
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    int insert(Dealership record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALERSHIP
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    Dealership selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALERSHIP
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    List<Dealership> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEALERSHIP
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    int updateByPrimaryKey(Dealership record);
}