package mybatis.model;

public class CarClient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR_CLIENT.CARS_ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    private Integer carsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR_CLIENT.CLIENTS_ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    private Integer clientsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR_CLIENT.CARS_ID
     *
     * @return the value of PUBLIC.CAR_CLIENT.CARS_ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public Integer getCarsId() {
        return carsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR_CLIENT.CARS_ID
     *
     * @param carsId the value for PUBLIC.CAR_CLIENT.CARS_ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public void setCarsId(Integer carsId) {
        this.carsId = carsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR_CLIENT.CLIENTS_ID
     *
     * @return the value of PUBLIC.CAR_CLIENT.CLIENTS_ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public Integer getClientsId() {
        return clientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR_CLIENT.CLIENTS_ID
     *
     * @param clientsId the value for PUBLIC.CAR_CLIENT.CLIENTS_ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public void setClientsId(Integer clientsId) {
        this.clientsId = clientsId;
    }
}