package mybatis.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */

    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.AMOUNT_PAID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    private Double amountPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.MILES_DRIVEN
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    private Integer milesDriven;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.SURNAME
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.ID
     *
     * @return the value of PUBLIC.CLIENT.ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.ID
     *
     * @param id the value for PUBLIC.CLIENT.ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.AMOUNT_PAID
     *
     * @return the value of PUBLIC.CLIENT.AMOUNT_PAID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public Double getAmountPaid() {
        return amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.AMOUNT_PAID
     *
     * @param amountPaid the value for PUBLIC.CLIENT.AMOUNT_PAID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public void setAmountPaid(Double amountPaid) {
        this.amountPaid = amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.MILES_DRIVEN
     *
     * @return the value of PUBLIC.CLIENT.MILES_DRIVEN
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public Integer getMilesDriven() {
        return milesDriven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.MILES_DRIVEN
     *
     * @param milesDriven the value for PUBLIC.CLIENT.MILES_DRIVEN
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public void setMilesDriven(Integer milesDriven) {
        this.milesDriven = milesDriven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.NAME
     *
     * @return the value of PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.NAME
     *
     * @param name the value for PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.SURNAME
     *
     * @return the value of PUBLIC.CLIENT.SURNAME
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.SURNAME
     *
     * @param surname the value for PUBLIC.CLIENT.SURNAME
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}