package mybatis.model;

public class Dealership {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEALERSHIP.ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEALERSHIP.NAME
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEALERSHIP.ID
     *
     * @return the value of PUBLIC.DEALERSHIP.ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEALERSHIP.ID
     *
     * @param id the value for PUBLIC.DEALERSHIP.ID
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEALERSHIP.NAME
     *
     * @return the value of PUBLIC.DEALERSHIP.NAME
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEALERSHIP.NAME
     *
     * @param name the value for PUBLIC.DEALERSHIP.NAME
     *
     * @mbg.generated Tue Apr 07 17:43:57 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}